---
title: 'Review for Exam 3'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, rladies, rladies-fonts, "my-theme.css"]
    incremental: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r, echo = F, results = 'hide', message=FALSE}
library(tidyverse)
library(broom)
library(palmerpenguins)
penguins = penguins

penguins$group = rep(c("group 1", "group 2", "group 3"), length.out = nrow(penguins))
penguins$group = factor(penguins$group)
```

## Final Exam

What it covers:

- Heavily weighted towards the last unit, but stuff from earlier in the semester (maybe even 1 or 2 things from Fall semester) creep in.
- Similar to all the exams thus far...nothing new; more writing heavy
- Knowing what to use and when to use it!

--

What it doesn't cover:

- `R` code
- Very specific things from the Fall
- Very specific things from Exams 1 & 2 -- we've built up from there

---

class: inverse, center, middle

# Continuing your statistics journey

---

## Mandatory

Research Designs & Methods (Psych 5011) with Ian Dobbins

- Required for Psych
- If you're not in Psych, you should email him... 

---

## In Psychological & Brain Sciences 

If `R` was really hard and you don't know what you're doing still...
- Applied Statistical Analysis with R (Psych 4175) with me!

--

If you are ready to take the next steps...
- Selected Topics in Design and Statistics (Psych 5012) with Mike Strube
- Hierarchical Linear Models (Psych 5068) with Mike Strube
- Applied Multivariate Analysis (Psych 516) with Mike Strube
- Applied Longitudinal Data Analysis (Psych 5065) with Josh Jackson
- Applied Bayesian Statistics for Psychologists	(Psych 5167) with Josh Jackson

---

## Outside Psychological & Brain Sciences

Cognitive, Computational, and Systems Neuroscience
- ACCSN (BME 519) with me and Dennis Barbour

--

The Brown School
- Structural Equation Modeling
- Survival Analysis
- DON'T take Biostats or Applied Linear Modeling

--

Political Science, Biostatistics (on med campus) exist, but I'm not familiar with those classes

--

New program in Division of Computational & Data Sciences

---

## Wanna be a showoff? 

Graduate Certificate in Quantitative Data Analysis

- Students must be enrolled in programs in Psychology, Economics, Education, or Anthropology
- If that isn't you, it still has a good list of classes to take!

https://psych.wustl.edu/graduate-certificate

---

class: inverse, middle, center

# Thank you for a great year! 
# `r emo::ji("celebrate")` `r emo::ji("tada")`

---
## Thought questions

.tiny[Spend roughly 10-15 minutes with friends describing each. Be as thorough as possible]

.small[


- What is the problem multilevel modeling is trying to solve? Can you explain fixed & random effects? Can you describe between-person effects and within-person effects? 

- What is the problem resampling methods help us overcome? Can you describe the process? If I gave you a snippet of code, could you read it through and more or less understand what is going on? 

- What problem is logistic regression trying to solve? Why can't we use linear regression? How do we derive our coefficients in logistic regression? Can you interpret the output?

- What was the main takeaway from Yarkoni & Westfall? What is cross-validation, overfitting, and regularization? When can we implement these tools? What is the bias-variance tradeoff and how does that relate to the terms listed earlier?  
]


