---
title: "Homework Assignments"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

Homework assignments will appear here. You'll be able to access the assignment, as well as any data that may be used. Homework assignments will be posted **at least one week** before they are due. Submit homework assignments via Canvas by the due date and time.

Note that this semester you will be making your RMarkdown/RNotebook (anything with the extension `.Rmd`) files on your own. If you need help, within RStudio, go to Help > Cheatsheets and select either the R Markdown Cheat Sheet or the R Markdown Reference Guide for help with formatting. You may also contact Shelly, Violet, or Chan with any questions or issues when knitting to HTML.

## Homework 1
- [Homework 1 is here](homework/homework1.html)
- Due on 2/8 by 9:30am
- Peer Review is due on 2/11 by 9:30am

## Homework 2
- [Homework 2 is here](homework/homework2.html)
- Due on 2/24 by 9:30am
- Peer Review is due on 2/27 by 9:30am

## Homework 3
- Homework 3 has not been posted yet
- Due on 3/22 by 9:30am
- Peer Review is due on 3/25 by 9:30am

## Homework 4
- Homework 4 has not been posted yet
- Due on 4/14 by 9:30am
- *Note: __DO NOT PUT THIS ONE OFF__. It's on the longer side and on interactions, which can be tricky. Best to not procrastinate this time.*
- Peer Review is due on 4/17 by 9:30am

## Homework 5
- Homework 5 has not been posted yet
- Due on 4/28 by 9:30am
- Peer Review is due on 5/1 by 9:30am
