---
title: "Psych 5067: Quantitative Methods II"
subtitle: "Department of Psychological & Brain Sciences, Washington University in St. Louis"
author: "Spring 2021. Instructor: Shelly R. Cooper"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

# Announcements

#### **List of Zoom Check-in Dates -- 1/27**

Remember that this semester you must attend at least 4 Zoom check-ins. There are 10 possible. They all will be on Thursdays, except for the very last check-in (noted below). You can attend any 4 that you want. For instance, if your AI is Violet, you are still totally welcome to attend a check-in with Chan. Here is a list of dates so you can put them on your calendar. Please note that in Canvas, there is also a link to a `.ics` file which will sync with your calendar software (I use Google Calendars). Dates:

- 2/4 with Violet
- 2/11 with Chan
- 2/18 with Shelly
- 2/25 with Violet -- REVIEW SESSION
- 3/4 with Shelly
- 3/18 with Chan
- 4/1 with Shelly
- 4/15 with Violet
- 4/22 with Chan
- 5/4 with Shelly (NOTE: This is a TUESDAY!)

#### **Update R & RStudio**

Before jumping into the semester, now is a good time to update your software. Make sure you have a solid internet connection before doing anything!Here's my suggested order of operations:

- Update computer software first, if needed 
- Update R (not RStudio). Once opened, go to R > Check for updates. If there is a new update, it will ask if you want to visit the CRAN. Type the letter `y` and hit enter. This should open up a webpage where you can download/install the latest version of R. You do *not* need to uninstall anything; it will do it for you.
- Update RStudio. On Macs, you can do this by going to Help > Check for updates. I think it's the same for PCs, but it might be located under a different menu. Follow the directions for installation.
- After it's done, re-open RStudio. Go to your Packages tab and click the green icon for Update. It will list all of your packages that have new updates available. I usually pick select 10-15 at a time just to not overwhelm my computer, but it's totally up to you. If at any point one of these packages says `There are binary versions available but the source versions are later. Do you want to install from sources the package which needs compilation?` go ahead and type `y` into the console and hit enter. Remember, with installing and updating packages, you'll get a lot of scary red text and it'll be doing a lot of stuff you don't understand. That's ok! When it's working, you will see a red stop sign in the top right of the Console pane. Don't do anything until that red icon is gone -- the icon means it's still working. 

If you come across any errors in the updating process, please take a screenshot and send it to Shelly, Violet, or Chan asap! 

# Overview

This course is the second in a two-course sequence that introduces necessary skills and knowledge for carrying out statistical analyses in the social sciences. The course has an applied focus for psychological research, but theoretical details will be emphasized when they facilitate understanding of key concepts. In other words, we will strike a balance between learning how to do statistics and knowing why we are doing it a particular way. Mastering both will facilitate generalization to new problems and techniques. We will primarily be covering regression analyses throughout this semester, including extensions of classic regression analyses.

## Instructors

**Shelly Cooper** -- [shelly.cooper@wustl.edu](mailto:shelly.cooper@wustl.edu)

- `r fontawesome::fa("calendar-alt")` [Schedule a 30min meeting](https://calendly.com/shelly-cooper/30min)

**Violet Brown** -- [violet.brown@wustl.edu](mailto:violet.brown@wustl.edu)

- Office Hours: By appointment & in "check-in" times
- *If you are in Psychology or Computational & Data Sciences*

**Chan Hyung Park** -- [chanhyungpark@wustl.edu](mailto:chanhyungpark@wustl.edu)

- Office Hours: By appointment & in "check-in" times
- *If you are in Business, Movement Science, PNP, Speech & Hearing*


# Materials

## Textbook

We will primarily be referring to chapters in [_Learning Statistics with R_](https://learningstatisticswithr-bookdown.netlify.com/index.html) by Danielle Navarro. This textbook is available for free online. You may choose to purchase a paper copy if you wish, but it is not required. Additional readings assignments will be posted here. 


## Resources for R and RStudio

While we will be covering the use of R and RStudio extensively in both lecture and lab, one of the key skills required to use R is the ability to find answers on the Internet. The R commmunity (sometimes referred to as the useR community) tends to be friendly and helpful and enjoys solving R-related problems in their spare time. For that reason, many common questions or problems have been posted to spaces online and answered by smart people. Finding and deciphering those answers is the key skill you should seek to hone this year. It's much more important than remembering function names. 

Here are some sites where you can find the answers to many R questions and learn new tricks:

### For learning the basics
 - [_YaRrr, the Pirate's Guide to R_](https://bookdown.org/ndphillips/YaRrr/) by Nathaniel Phillips
 - [_R for Data Science_](https://r4ds.had.co.nz/) by Hadley Wickham
 - [_R Cookbook_](http://www.cookbook-r.com/) by Winston Chang
 - [_An Introduction to Statistical Learning_](http://www-bcf.usc.edu/~gareth/ISL) by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani

### For plotting

  - The [Graphs chapter of _R Cookbook_](http://www.cookbook-r.com/Graphs/) by Winston Chang
  
### Quick resources

  - [Cheat Sheets](https://www.rstudio.com/resources/cheatsheets) 
  - [Quick-R](https://www.statmethods.net) 
  
### Online forums
  - [Stack Overflow](https://stackoverflow.com) \
  - [Cross Validated](https://stats.stackexchange.com)



