---
title: "Lecture Videos"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

## Week 1

#### 1/26
- [Introduction](https://youtu.be/ZX8ck7Y0c1g)
- [Zoom Check-in with Everyone](https://wustl.zoom.us/j/91992423151?pwd=Y1hoTnVoMlhKcFdZblY2Q0FGczNrZz09)
- HW 1 posted

#### 1/28
- [GLM & Categorical Predictors](https://youtu.be/-ew-txPO3p4)

## Week 2

#### 2/2
- [Correlation](https://youtu.be/WHE4t5t1EhQ)

#### 2/4
- [Univariate Regression](https://youtu.be/EQgLnwxNv_4)
- [Zoom Check-in with Violet](https://wustl.zoom.us/j/92420044586?pwd=S2ZxSms4UTRuc2xsMXZzVXRGQ3J4UT09)

## Week 3

#### 2/9
- [Univariate Regression 2](https://youtu.be/WVYRdbI9Qwg) 
- **HW 1 Due by 10am**

#### 2/11
- [Partial Correlations](https://youtu.be/-r4sTHdZBCM) *Note: I say the words "correlation", "semi partial correlation", and "partial correlation" a million times in this video -- so it turns into a bit of a tongue twister! I have edited the video so that it's hopefully clear, but please reach out on Slack if there's any part that is confusing.*
- [Zoom Check-in with Chan](https://wustl.zoom.us/j/92420044586?pwd=S2ZxSms4UTRuc2xsMXZzVXRGQ3J4UT09)
- [Recording of Zoom Check-in with Chan](https://wustl.box.com/s/dlapv2fq0fqm2pbvmnf5z16ouhxgtyq9)

## Week 4

#### 2/16
- [Multiple Regression 1](https://youtu.be/gIrE84p25Gk)

#### 2/18
- [Multiple Regression 2](https://youtu.be/Tt5ygK2wunM)
- [Zoom Check-in with Shelly](https://wustl.zoom.us/j/92420044586?pwd=S2ZxSms4UTRuc2xsMXZzVXRGQ3J4UT09)
- [Recording of Zoom Check-in with Shelly](https://wustl.box.com/s/gyawifblek4bn7fnx02kqva37r2lfy1z)

## Week 5

#### 2/23
- [Multiple Regression 3](https://youtu.be/qvl3AygycdQ)

#### 2/25
- No new material
- [Zoom Check-in with Violet]((https://wustl.zoom.us/j/92420044586?pwd=S2ZxSms4UTRuc2xsMXZzVXRGQ3J4UT09))
  + [Here are the review questions](readings/Review Session 1.pdf), created by Violet. You should do these practice problems *before* coming to Thursday's review. (You can still attend if you haven't completed them -- but to get the most out of it, it's best if you come prepared)
  + [Here is the recording from this check-in](https://wustl.box.com/s/r0wve2vnweq1o4fd3a7x6zh8r9kybtdv) and [here is the transcript of this session](https://wustl.box.com/s/3v078ld75s18coenq0czjb42gp95i51n) (note that you'll need to download the transcript and open it as a text file)
  
## Week 6

#### 3/2
- Wellness Week 1; no new material

#### 3/4
- Wellness Week 1; no new material
- [Zoom Check-in with Shely](https://wustl.zoom.us/j/92420044586?pwd=S2ZxSms4UTRuc2xsMXZzVXRGQ3J4UT09)

## Week 7

#### 3/9
- **Exam 1 Opens at 10am**

#### 3/11
- **Exam 1 DUE by 10am**

## Week 8

#### 3/16
- [Assumptions & Diagnostics](https://youtu.be/t9AE_tSzAbk)

#### 3/18
- [Causal Models](https://youtu.be/PFVzK_swzG8)