---
title: "Syllabus"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

# Weekly schedule

LSR readings can be found in the free, online textbook, [*Learning Statistics with R*](https://learningstatisticswithr-bookdown.netlify.com/index.html) by Danielle Navarro. For those interested in taking notes, I recommend the use of the [Hypothes.is](http://Hypothes.is) app to annotate webpages. I will note that the formatting of the book online is wonky in a few places. If this bothers you, or you prefer to work offline, you can download a [PDF version](https://learningstatisticswithr.com/lsr-0.6.pdf) of the book. We will also use An Introduction to Statistical Learning (**ISLR**) for supplemental readings. You can find a free version of [ISLR here](https://www.statlearning.com/). You can use either the first or second version. All other readings will be provided on this page, in the lecture slides, and on our GitHub page.

**PR = Peer Review**

| Week | Date | Topic | Readings | HW Due |   |
|------------|------------|------------|------------|------------|------------|
| 1 | 1/14 | Recap & GLM Intro |  |  |  |
| \- | 1/16 | Data Management | [Human Fallibility](readings/HumanFallibility_DataManagement.pdf) |  |  |
| 2 | 1/21 | GLM & Categorical Predictors | Ch. 13-14 (review) |  |  |
| \- | 1/23 | Correlation | [Chapter from Revelle](readings/CorrelationRevelle.pdf) |  |  |
| 3 | 1/28 | Catch up |  |  |  |
| \- | 1/30 | Univariate Regression | [MR Cohen](readings/Cohen-MR.pdf); Ch. 15.1 - 15.2 |  |  |
| 4 | 2/4 | Univariate Regression |  |  |  |
| \- | 2/6 | Partial Correlations | Ch. 15.3 - end of chapter | **HW 1 DUE 2/9 11:59pm** |  |
| 5 | 2/11 | Multiple Regression |  |  |  |
| \- | 2/13 | Multiple Regression |  |  |  |
| 6 | 2/18 | **Exam 1** |  | **HW 2 DUE 2/19 11:59pm** |  |
| \- | 2/20 | Assumptions and Diagnostics |  |  |  |
| 7 | 2/25 | Interactions I |  |  |  |
| \- | 2/27 | Interactions II (Factorial ANOVA) | Ch. 16, [Myers Ch. 9](readings/anova1-myers.pdf) |  |  |
| 8 | 3/4 | Interactions III | [Myers Ch. 10](readings/anova2-myers.pdf) |  |  |
| \- | 3/6 | Interactions IV (Power & Effect Size) |  | **HW 3 DUE 3/7 11:59pm** |  |
| 9 | 3/11 | **Spring Break** |  |  |  |
| \- | 3/13 | **Spring Break** |  |  |  |
| 10 | 3/18 | Interactions V (Polynomials) |  |  |  |
| \- | 3/20 | Logistic Regression/GLM | [Cohen Logistic](readings/Logistic-Cohen.pdf) |  |  |
| 11 | 3/25 | Random/Flex/Catch-up |  |  |  |
| \- | 3/27 | **Exam 2** |  | **HW 4 DUE 3/28 11:59pm** |  |
| 12 | 4/1 | Machine Learning | [Yarkoni & Westfall](readings/Yarkoni%20Westfall%20PPS.pdf) |  |  |
| \- | 4/3 | Resampling Methods *Guest Lecture: Ran Zhang* |  |  |  |
| 13 | 4/8 | Qualitative Methods *Guest Lecture: Amy Eyler* |  |  |  |
| \- | 4/10 | Bayes Intro |  |  |  |
| 14 | 4/15 | MLM Intro |  |  |  |
| \- | 4/17 | TBD |  | **HW 5 DUE 4/18 11:59pm** |  |
| 15 | 4/22 | AI Intro *Guest Lecture: Josh Oltmanns* |  |  |  |
| \- | 4/24 | **FINAL** |  |  |  |

# Overview

### From the course catalog:

Continuation of Psych 5066. Introduction to multiple regression/correlation analysis. Topics include bivariate and multiple correlation and regression, regression diagnostics, representation of nominal or qualitative variables, polynomials, logistic regression, interactions, ANOVA, analysis of covariance, repeated measures, power calculations, and Bayesian approaches to the general linear model

### Holistic view:

This course is the second in a two-course sequence that introduces necessary skills and knowledge for carrying out statistical analyses in the social sciences. The course has an applied focus for psychological research, but theoretical details will be emphasized when they facilitate understanding of key concepts. In other words, we will strike a balance between learning how to do statistics and knowing why we are doing them in a particular way. Mastering both will facilitate generalization to new problems and techniques. We will primarily be covering regression analyses throughout this semester, including extensions of classic regression analyses.

### Prerequisites:

Completion of Psych 5066

### Learning Objectives:

-   **Advanced Statistical Theory:** Develop a deep understanding of advanced statistical theories and principles, including hypothesis testing and inference, particularly as they relate to the general linear model

<!-- -->

-   **Data Analysis Techniques:** Apply advanced data analysis techniques such as regression analysis and be able to visualize results.

-   **Statistical Software Proficiency:** Gain proficiency in using R statistical software for data manipulation, analysis, and visualization.

-   **Innovative Quantitative Methodologies:** Explore and apply innovative quantitative methodologies, staying on top of emerging trends in the field.

# Graded materials

Your final grade is comprised of:

-   5 Homework: 5% each, 25% total
-   Exam 1: 30% (90% written, 10% oral)
-   Exam 2: 25% (90% written, 10% oral)
-   Exam 3: 20% (90% written, 10% oral)

## Exams

There are 3 exams total, each with a written portion and an oral portion. They will follow similar formats to last semester where the written portion is a little more math-heavy (although you will still be asked to write interpretations etc.) and the oral exam is a little more theoretical and/or applied in context.

The last exam is very similar to last semester, where it is technically a cumulative exam, but emphasis is on the last third of the class and broad topics/analytics from the first two thirds of the class.

Together, the first exam is worth 30% of your grade, the second exam is worth 25% of your grade, and the last exam is worth 20% of your grade.

**New Rule**: If you have something going on in life that you think will impede you from doing your best on an exam, please come talk to me (even if it's like 5 minutes before we start!). Family emergency, sudden news of a loved one, illness, bereavement, etc. *Once you see an exam, you will not be able to make-up or retake the test.* I would much prefer that you talk to me and we agree that you take the exam at a later date, rather than trying to take it first, seeing how you do, then asking for a redo. You are graduate students, and I think by now you've learned that I'm not particularly scary -- I will always work with you and very much want you to succeed!

## Homework assignments

Homework assignments are intended to gauge your ability to apply the topics covered in class to the practice of data analysis. Homework assignments are to be done using `R` and RMarkdown; completed assignments should be submitted to Canvas. Please submit BOTH your **.Rmd** and **.html** file. Please do *not* use PDF or Word documents. There will be 5 assignments in total, each worth 5% of your grade.

I will specify exact due dates, and all will be required by 11:59pm. Grading will go by the following rubric:

-   5/5: Completed all parts of the assignment, and results/interpretations were mostly correct (with maybe a few minor errors along the way)
-   4/5: Completed all parts of the assignment, and \~25% of the results/interpretations are incorrect
-   3/5: Completed all parts of the assignment, however \~50% of the results/interpretations are incorrect. Or, parts of the assignment are missing but what is there is correct.
-   2/5: Parts of the assignment are missing, and there are substantial issues with the results/interpretation
-   1/5: Nearly all of the assignment is missing, but something was turned in
-   0/5: No assignment submitted

All of this to say that you can still get a 5 out of 5 even if you get a few things wrong here and there. HW assignments should boost your grades, not hurt them.

You may work with your peers on homework assignments, with the following caveats:

1.  Your code cannot be 100% identical to your peer's code (trust me, we can tell). It’s one thing to work together and consult, but it’s another thing to copy someone else’s assignment. If it is determined that someone copied an entire homework assignment, both parties will be given automatic zero.
2.  If you work with someone, you *must* acknowledge them in the assignment itself.

**AI Policy** Given the nature of written in-person exams and oral exams, there is no way to feasibly use AI in these settings. However, AI is particularly helpful for coding. I am OK with you using AI tools for your homework assignments with the following caveats: 1. You are the adult in the room. That means it's up to you to be able to carefully evaluate what it gives you. AI is often wrong so you'll need to be careful here. 2. You must paste the link to the "conversation" in your HW assignments so that we can back-trace what you prompted and how it responded. A url that does not work will be considered a violation of academic integrity. 3. If the AI is wrong and you do not catch it, this will count against you. You can't blame the AI.

## Final Grading Rubric

All assignments and examinations are mandatory. If you need to miss an exam you must get in touch with me as soon as possible. Rescheduling of exams will be considered on a case by case basis, but I am *not* required to approve a rescheduled exam.

\begin{equation}
\begin{split}

& \text{> 93% = A} \\
& \text{90% - 92.99% = A-} \\
& \text{87% - 89.99% = B+} \\
& \text{83% - 86.99% = B} \\
& \text{80% - 82.99% = B-} \\
& \text{77% - 79.99% = C+}

\end{split}

\begin{split}

& \text{73% - 76.99% = C} \\
& \text{70% - 72.99% = C-} \\
& \text{67% - 69.99% = D+} \\
& \text{63% - 66.99% = D} \\
& \text{60% - 62.99% = D-} \\
&\text{< 50% = F}

\end{split}
\end{equation}

# Learning from Crappy Years

Life has been weird since the pandemic. But instead of burying our heads in the sand and forgetting they existed, let's at least extract some things and incorporate them into our lives. For this class, here's what that means...

### Staying Connected

The past few years have been lonely. Although we're back in person, we still might feel that residual loneliness. On top of that, learning stats, learning to code, and grad school in general can be really scary -- impostor syndrome is real! The best thing we can do to combat these feelings is to stay connected to one another. Here's how we'll accomplish this in our class:

-   We will have a dedicated class Slack work space (see upper right corner of website for link). You can post questions that everyone can see, or make use of direct messaging. Shelly or the AIs will respond to your questions on Slack (if your peers don't respond first!). This is really great for one-off questions, or if you need some quick clarification on something. We will also have a dedicated channel for silly programming and stats memes, because humor is important when you're learning a skill like coding, in which you'll repeatedly fail. Slack is not required *per se*, but it is **highly encouraged**.

### Be Considerate and Kind

-   It is OK to not be OK. If you tell me you're having trouble, I'm not going to judge you or think less of you. I hope you will do the same for me. I will work with you to make sure we have a reasonable plan in place should something come up. *However*, this does require you telling me "hey, I'm not OK".
-   You are always welcome to come talk to me about things that you're going through. If I can't help you, I usually know someone who can help -- or I can at least give you some resources and point you in the right direction.
-   If you are struggling or need extra help, please just ask. I promise I will work with you.

### Attendance & In-person Etiquette

-   I expect all students to be in class if they are able (not sick, not at a conference etc.). The best way to succeed is to come to class. Your chosen profession requires mastery of these skills! Come to class!
-   I will take attendance. **If you are absent for 2 class periods in a row, *and you have not reached out to either the instructor or the AIs*, I will assume that something is wrong.** When I have concerns about a graduate student, I contact their PI. I will do the same here.
    -   If you reach out and say you need to miss class for whatever reason, then there is no need for me to contact your PI. I know you are alive and well (or at least getting well).
    -   This policy comes out of concern for you! It's hard to succeed if you aren't in class, and I really want you to succeed!
    -   You are adults. Come to class when you can. Let me know when you can't (quick email or Slack is OK).
-   **If you are not feeling well, don't come to class!!** You have access to the slides and you can ask a friend for notes.
-   If there is even a *hint* of being sick, I prefer you stay home. If you are 100% sure it's nothing contagious -- like allergies, I still ask that you wear a mask and sit away from other students.
-   Most people will have electronics with them in class. Drinks should have a lid on them so that if they spill, we hopefully aren't ruining yours or another person's laptop/tablet/phone etc. Be careful!
-   Occasionally, I'll ask you to get into small groups and chat about something. Be aware that other people might not be super comfortable being physically close together. Maintain appropriate distance, and if a classmate asks you to step back a bit, please do so.

# Policies & Resources

**Contact Hours:**

This is a 3 credit course and I anticipate that we will meet for all class periods scheduled. However, should anything arise that would prevent us from meeting in class, we will make up all contact hours. This will be addressed on a case-by-case basis but may include: synchronous Zoom class, asynchronous recording of lecture material, Canvas assignment etc.

**UNIQUE TO SPRING 2025:**

I am pregnant and due mid April. I have planned a great semester and therefore do not anticipate any disruptions to the course. Here is the plan:

-   See class schedule above for topics on a day-by-day basis

-   Once I go into labor, **Josh Jackson** will become the instructor for the course. You can reach him at [**j.jackson\@wustl.edu**](mailto:j.jackson@wustl.edu){.email}

-   Please note that all the same class policies will apply when he is in charge! The grading will remain the same, and the exams have already been made – he is simply the point person for grade related questions and will give the remaining lectures. The class does not magically change.

-   In the off chance that class must be canceled or rescheduled, note that all contact hours will be made up in some capacity as per the above Contact Hours section.

**University Code of Conduct:**

-   Any student found guilty of academic misconduct, such as cheating, plagiarizing, forgery, or furnishing false information to a University official will be subject to consequences including failing the class, suspension from the University, or expulsion from the University. Frankly, you're in graduate school, and the purpose of work is to create opportunities to learn and improve. Even if cheating helps you in the short term, you'll quickly find yourself ill-prepared for the career you have chosen. If you find yourself tempted to cheat, please come speak to me about an extension and developing tools to improve your success.
-   Please see the official [University Code of Conduct](https://wustl.edu/about/compliance-policies/academic-policies/university-student-judicial-code/)

**Special Accommodations:**

-   This includes but is not limited to a learning, sensory, or physical disability or any other diagnosis that requires special accommodations and/or assistance with lectures, reading, written assignments, and/or exam taking
-   Contact [Disability Resources](https://students.wustl.edu/disability-resources/) at [disabilityresources\@wustl.edu](mailto:disabilityresources@wustl.edu) or call 314-935-5970
-   Please also contact me as soon as possible if you need special accommodations. Once I have the Accommodation Letter from [Disability Resources](https://students.wustl.edu/disability-resources/), we can discuss ways to modify the course experience for you.

**Mental & Physical Health:**

-   [Habif Health and Wellness Center](https://students.wustl.edu/habif-health-wellness-center/), email [HabifInfo\@wustl.edu](mailto:HabifInfo@wustl.edu) or call 314-935-6666

**WUSTL Police Department:**

-   For an on campus emergency, call 314-935-5555
-   For an off campus emergency, call 911

**Relationship or Sexual Violence (including sexual harassment and stalking):**

-   Contact a licensed RSVP counselor (confidential, with some limited information being shared as needed with the appropriate university administrator(s)) at [rsvpcenter\@wustl.edu](mailto:rsvpcenter@wustl.edu) or call 314-935-3445
-   Contact the university's Title IX Director, Ms. Jessica Kennedy, at [jwkennedy\@wustl.edu](mailto:jwkennedy@wustl.edu) or call 314-935-3118

***You can always come to me!** Period. However, if you come to me with any issues surrounding child abuse, suicidal tendencies, or sexual assault, sexual discrimination, sexual harassment, dating violence, domestic violence or stalking, I am required to report these to their appropriate administrators. Washington University faculty and administrators strive to maintain confidentiality, but some information may need to be disclosed when it is a matter of safety.*
