---
title: 'CONGRATULATIONS'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, rladies, rladies-fonts, "my-theme.css"]
    incremental: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


## This Time

- Final Exam
- Additional Classes
- Party

---

## Final Exam

What it covers:

- Topics from entire semester (maybe even 1 or 2 from the Fall)
- Similar to all the exams thus far...nothing new
- Includes logistic regression, ML, MLM etc.

--

What it doesn't cover:

- `R` code
- Very specific things from the Fall
- Very specific things from Exam 1 -- we've built up from there

---

## Final Exam

Works just like last semester:

- Will post on Canvas on **5/6**
- All exams must be in by **5/13** at noon (full week)
- Once you access it on Canvas, you have 48 hours to complete it
- You get to pick which 2 days you finish the exam!
- **DO NOT PLAN ON TAKING THE EXAM THE DAY AFTER VACCINE #2**
- No time limit on questions; email all 3 of us

---

## Course Evals

- Open until May 13th at 10pm
- Last 3 questions are most important!

---

class: inverse, center, middle

# Continuing your statistics journey

---

## Mandatory

Research Designs & Methods (Psych 5011) with Ian Dobbins

- Required for Psych
- If you're not in Psych, you should email him... 

---

## In Psychological & Brain Sciences 

If `R` was really hard and you don't know what you're doing still...
- Applied Statistical Analysis with R (Psych 4175) with me!

--

If you are ready to take the next steps...
- Selected Topics in Design and Statistics (Psych 5012) with Mike Strube
- Hierarchical Linear Models (Psych 5068) with Mike Strube
- Applied Multivariate Analysis (Psych 516) with Mike Strube
- Applied Longitudinal Data Analysis (Psych 5065) with Josh Jackson
- Applied Bayesian Statistics for Psychologists	(Psych 5167) with Josh Jackson

---

## Outside Psychological & Brain Sciences

Cognitive, Computational, and Systems Neuroscience
- ACCSN (BME 519) with me and Dennis Barbour

--

The Brown School
- Structural Equation Modeling
- Survival Analysis
- DON'T take Biostats or Applied Linear Modeling

--

Political Science, Biostatistics (on med campus) exist, but I'm not familiar with those classes

--

New program in Division of Computational & Data Sciences

---

## Wanna be a showoff? 

Graduate Certificate in Quantitative Data Analysis

- Students must be enrolled in programs in Psychology, Economics, Education, or Anthropology
- If that isn't you, it still has a good list of classes to take!

https://psych.wustl.edu/graduate-certificate

---

class: inverse, middle, center

# Party!  `r emo::ji("celebrate")` `r emo::ji("tada")`
